### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jonasftw** [erkexzcx/bbtmvbot#6]
bbtmvbot-master$ go build -o bbtmvbot
# github.com/erkexzcx/bbtmvbot
/usr/bin/ld: $WORK/b001/_pkg1_.a(_x011.o): undefined reference to symbol 'pthread_mutex_trylock@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by erkexzcx** [comment]
Check `dev` branch and its README.md. I'm rewriting this `bbtmvbot` project. This was my first Golang serious project and first version is just a trash :D  Hopefully second version would be more maintainable.

**Comment by erkexzcx** [comment]
New code in `master` branch. Also in README.md added link to my hosted (in cloud) instance.
